/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Client_Keylogger_Keylogger */

#ifndef _Included_Client_Keylogger_Keylogger
#define _Included_Client_Keylogger_Keylogger
#ifdef __cplusplus
extern "C" {
#endif
#undef Client_Keylogger_Keylogger_MIN_PRIORITY
#define Client_Keylogger_Keylogger_MIN_PRIORITY 1L
#undef Client_Keylogger_Keylogger_NORM_PRIORITY
#define Client_Keylogger_Keylogger_NORM_PRIORITY 5L
#undef Client_Keylogger_Keylogger_MAX_PRIORITY
#define Client_Keylogger_Keylogger_MAX_PRIORITY 10L
/*
 * Class:     Client_Keylogger_Keylogger
 * Method:    startKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Client_Keylogger_Keylogger_startKey
  (JNIEnv *, jobject);

/*
 * Class:     Client_Keylogger_Keylogger
 * Method:    stopKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Client_Keylogger_Keylogger_stopKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
